bmw:
  clientId: "<BMW_CLIENT_ID>"
  # Portal "Benutzername" (GCID)
  gcid: "<BMW_GCID>"
  # Portal "Topic" (VIN)
  vin: "<VEHICLE_VIN>"
  tokensFile: "bmw.tokens.json"
  deviceCodeEndpoint: "https://customer.bmwgroup.com/gcdm/oauth/device/code"
  tokenEndpoint: "https://customer.bmwgroup.com/gcdm/oauth/token"
abrp:
  apiKey: "<ABRP_API_KEY>"
  userToken: "<ABRP_USER_TOKEN>"
mqtt:
  # Portal "Host" + "Port"
  brokerUrl: "mqtts://customer.streaming-cardata.bmwgroup.com:9000"
  tls: true
mapping:
  soc:
    - "vehicle.powertrain.electric.battery.stateOfCharge.target"
  is_charging:
    - "vehicle.drivetrain.electricEngine.charging.status"
  is_plugged_in:
    - "vehicle.drivetrain.electricEngine.charging.plugConnectionState"
  lat:
    - "location.latitude"
  lon:
    - "location.longitude"
  speed:
    - "vehicle.speed"
  power:
    - "vehicle.powertrain.electric.power"
rateLimitSeconds: 10
