bmw:
  clientId: "<BMW_CLIENT_ID>"
  # myBMW portal "Benutzername" (GCID)
  gcid: "<BMW_GCID>"
  # myBMW portal "Topic" (VIN)
  vin: "<VEHICLE_VIN>"
  tokensFile: "bmw.tokens.json"
  deviceCodeEndpoint: "https://customer.bmwgroup.com/gcdm/oauth/device/code"
  tokenEndpoint: "https://customer.bmwgroup.com/gcdm/oauth/token"
abrp:
  apiKey: "<ABRP_API_KEY>"
  userToken: "<ABRP_USER_TOKEN>"
mqtt:
  # myBMW portal "Host" + "Port"
  brokerUrl: "mqtts://customer.streaming-cardata.bmwgroup.com:9000"
  tls: true
  # Optional: override MQTT auth (default uses GCID + id token)
  # username: "<MQTT_USERNAME>"
  # password: "<MQTT_PASSWORD>"
  # Optional: choose which BMW token to use as password (id/access/refresh)
  # passwordToken: "id"
mapping:
  soc:
    - "vehicle.powertrain.electric.battery.stateOfCharge.target"
  is_charging:
    - "vehicle.drivetrain.electricEngine.charging.status"
  is_plugged_in:
    - "vehicle.drivetrain.electricEngine.charging.plugConnectionState"
  lat:
    - "location.latitude"
  lon:
    - "location.longitude"
  speed:
    - "vehicle.speed"
  power:
    - "vehicle.powertrain.electric.power"
rateLimitSeconds: 10
