bmw:
  clientId: "<BMW_CLIENT_ID>"
  # myBMW portal "Benutzername"
  username: "<BMW_BENUTZERNAME>"
  # myBMW portal "Topic"
  topic: "<BMW_TOPIC>"
  deviceCodeEndpoint: "https://customer.bmwgroup.com/gcdm/oauth/device/code"
  tokenEndpoint: "https://customer.bmwgroup.com/gcdm/oauth/token"
abrp:
  apiKey: "<ABRP_API_KEY>"
  userToken: "<ABRP_USER_TOKEN>"
bmwRest:
  enabled: true
  # intervalSeconds: 300
  # containerName: "abrp-live-connector"
  # technicalDescriptors:
  #   - "vehicle.drivetrain.batteryManagement.header"
mapping:
  soc:
    - "vehicle.drivetrain.batteryManagement.header"
  is_charging:
    - "vehicle.drivetrain.electricEngine.charging.status"
  is_plugged_in:
    - "vehicle.body.chargingPort.status"
    - "vehicle.powertrain.tractionBattery.charging.port.anyPosition.isPlugged"
  lat:
    - "vehicle.cabin.infotainment.navigation.currentLocation.latitude"
  lon:
    - "vehicle.cabin.infotainment.navigation.currentLocation.longitude"
  speed:
    - "vehicle.vehicle.avgSpeed"
  power:
    - "vehicle.powertrain.electric.battery.charging.power"
  charging_power:
    - "vehicle.powertrain.electric.battery.charging.power"
  remaining_charge_time:
    - "vehicle.drivetrain.electricEngine.charging.timeRemaining"
    - "vehicle.drivetrain.electricEngine.charging.timeToFullyCharged"
  heading:
    - "vehicle.cabin.infotainment.navigation.currentLocation.heading"
  elevation:
    - "vehicle.cabin.infotainment.navigation.currentLocation.altitude"
  remaining_range:
    - "vehicle.cabin.infotainment.navigation.remainingRange"
  tire_pressure_fl:
    - "vehicle.chassis.axle.row1.wheel.left.tire.pressure"
  tire_pressure_fr:
    - "vehicle.chassis.axle.row1.wheel.right.tire.pressure"
  tire_pressure_rl:
    - "vehicle.chassis.axle.row2.wheel.left.tire.pressure"
  tire_pressure_rr:
    - "vehicle.chassis.axle.row2.wheel.right.tire.pressure"
rateLimitSeconds: 10
logLevel: "info"
