services:
  abrp-live-connector:
    build: .
    container_name: abrp-live-connector
    environment:
      CONFIG_PATH: /config.yaml
    volumes:
      - ./config.yaml:/config.yaml:ro
      - ./data:/data
    restart: unless-stopped
