services:
  abrp-live-connector:
    build: .
    container_name: abrp-live-connector
    environment:
      CONFIG_PATH: /config/config.yaml
    volumes:
      - ./config:/config:ro
      - ./data:/data
    restart: unless-stopped
